### ISSUE TITLE
issue adding tasks "UUID has no attribute group"

### ISSUE THREAD

**Issue by TheBestJohn** [ralphbean/taskw#144]
Updating my local workflow, I've been setting up bugwarrior which uses taskw as a dependency. 

Python version: 2.7.18
Task version 2.5.4
taskw version 1.3.0

```bash
Traceback (most recent call last):
  File "/usr/local/bin/bugwarrior-pull", line 11, in <module>
    sys.exit(pull())
  File "/Users/jwarren/.asdf/installs/python/2.7.18/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jwarren/.asdf/installs/python/2.7.18/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jwarren/.asdf/installs/python/2.7.18/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jwarren/.asdf/installs/python/2.7.18/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jwarren/.asdf/installs/python/2.7.18/lib/python2.7/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/Users/jwarren/.asdf/installs/python/2.7.18/lib/python2.7/site-packages/bugwarrior/db.py", line 438, in synchronize
    new_task = tw.task_add(**issue)
  File "/Users/jwarren/.asdf/installs/python/2.7.18/lib/python2.7/site-packages/taskw/warrior.py", line 697, in task_add
    task['uuid'] = re.search(UUID_REGEX, stdout).group(0)
AttributeError: 'NoneType' object has no attribute 'group'```

**Comment by coddingtonbear** [comment]
~~So, I can't say for sure, but I can give you some insight into what might be going wrong here; spoiler alert: it's probably our local taskwarrior installation's fault somehow.~~  (@ryneeverett has explained to me that this might actually be a bug, but I'm leaving the description below because it's at least not inaccurate).

What we're doing at that step is sending information off to taskwarrior (via its stdin) to perform whatever operation (in this case: creating a new issue), and then looking at taskwarrior's stdout to see the new issue's UUID in the returned output.  In this particular case, we unexpectedly couldn't find a UUID in that output, resulting in that error you're seeing.

**Comment by ryneeverett** [comment]
I believe this is the error #141 aims to work around. See also https://github.com/ralphbean/bugwarrior/issues/805.

**Comment by TheBestJohn** [comment]
Thank you for the insight. This does seem to have been the issue. I started by running `task add test` and got back `created task 8`. Adding `verbose=yes` to my taskrc has popped back in the uuid.

**Comment by jayvdb** [comment]
This is causing 47 tests to fail.

**Comment by mhalano** [comment]
I have this problem when I was using bugwarrior. I installed manually with `pip` command the version from `develop` branch. It worked fine.
