### ISSUE TITLE
Test failures using taskwarrior 2.4.4

### ISSUE THREAD

**Issue by domenkozar** [ralphbean/taskw#98]
```
======================================================================
FAIL: taskw.test.test_datas.TestDBShellout.test_filtering_brace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/ybasldb42n05g7b7jsxz2f40jy3bwyj3-python2.7-nose-1.3.4/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/nix-build-python2.7-taskw-1.0.3.drv-0/taskw-1.0.3/taskw/test/test_datas.py", line 374, in test_filtering_brace
    eq_(len(tasks), 1)
AssertionError: 2 != 1

======================================================================
FAIL: taskw.test.test_datas.TestDBShellout.test_filtering_plus
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/ybasldb42n05g7b7jsxz2f40jy3bwyj3-python2.7-nose-1.3.4/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/nix-build-python2.7-taskw-1.0.3.drv-0/taskw-1.0.3/taskw/test/test_datas.py", line 393, in test_filtering_plus
    eq_(len(tasks), 1)
AssertionError: 3 != 1

======================================================================
FAIL: taskw.test.test_datas.TestDBShellout.test_filtering_qmark
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/ybasldb42n05g7b7jsxz2f40jy3bwyj3-python2.7-nose-1.3.4/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/nix-build-python2.7-taskw-1.0.3.drv-0/taskw-1.0.3/taskw/test/test_datas.py", line 423, in test_filtering_qmark
    eq_(tasks[0]['id'], 2)
AssertionError: 1 != 2

======================================================================
FAIL: taskw.test.test_datas.TestDBShellout.test_filtering_question_mark
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/ybasldb42n05g7b7jsxz2f40jy3bwyj3-python2.7-nose-1.3.4/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/nix-build-python2.7-taskw-1.0.3.drv-0/taskw-1.0.3/taskw/test/test_datas.py", line 451, in test_filtering_question_mark
    eq_(len(tasks), 1)
AssertionError: 2 != 1
```

**Comment by EdwardBetts** [comment]
This problems doesn't happen with any other version. Here is the output from tox:

      py27-tw22: commands succeeded
      py27-tw23: commands succeeded
      py27-tw24: commands succeeded
      py27-tw241: commands succeeded
      py27-tw242: commands succeeded
    ERROR:   py27-tw244: commands failed
      py27-tw250: commands succeeded
      py34-tw22: commands succeeded
      py34-tw23: commands succeeded
      py34-tw24: commands succeeded
      py34-tw241: commands succeeded
      py34-tw242: commands succeeded
    ERROR:   py34-tw244: commands failed
      py34-tw250: commands succeeded

**Comment by EdwardBetts** [comment]
Here is the upstream bug: https://bug.tasktools.org/browse/TW-1463

I think this is the fix: https://git.tasktools.org/projects/TM/repos/task/commits/6d9d896a3714b16ec3103a600b61d6c5f5f8597e

**Comment by domenkozar** [comment]
:+1:
