### ISSUE TITLE
"Invalid range end" for a description.startswith containing `\\[..\\]`

### ISSUE THREAD

**Issue by djmitche** [ralphbean/taskw#99]
```
CRITICAL:command:oh noes
TRACE Traceback (most recent call last):
TRACE   File "/home/dustin/code/taskwarrior/t/bugwarrior-prod/bugwarrior/command.py", line 62, in pull
TRACE     synchronize(issue_generator, config, main_section, dry_run)
TRACE   File "/home/dustin/code/taskwarrior/t/bugwarrior-prod/bugwarrior/db.py", line 342, in synchronize
TRACE     tw, key_list, issue, legacy_matching=legacy_matching
TRACE   File "/home/dustin/code/taskwarrior/t/bugwarrior-prod/bugwarrior/db.py", line 179, in find_local_uuid
TRACE     ('status', 'waiting'),
TRACE   File "/home/dustin/code/taskwarrior/t/bugwarrior-prod/sandbox/lib/python2.7/site-packages/taskw/warrior.py", line 606, in filter_tasks
TRACE     *query_args
TRACE   File "/home/dustin/code/taskwarrior/t/bugwarrior-prod/sandbox/lib/python2.7/site-packages/taskw/warrior.py", line 507, in _get_task_objects
TRACE     json = self._get_json(*args)
TRACE   File "/home/dustin/code/taskwarrior/t/bugwarrior-prod/sandbox/lib/python2.7/site-packages/taskw/warrior.py", line 504, in _get_json
TRACE     return json.loads(self._execute(*args)[0])
TRACE   File "/home/dustin/code/taskwarrior/t/bugwarrior-prod/sandbox/lib/python2.7/site-packages/taskw/warrior.py", line 494, in _execute
TRACE     raise TaskwarriorError(command, stderr, stdout, proc.returncode)
TRACE TaskwarriorError: ['task', 'rc:/home/dustin/.taskrc', 'rc.uda.bugzillasummary.type=string', 'rc.uda.bugzillasummary.label="Bugzilla Summary"', 'rc.uda.githubcreatedon.type=date', 'rc.uda.githubcreatedon.label="Github Created"', 'rc.uda.githubupdatedat.type=date', 'rc.uda.githubupdatedat.label="Github Updated"', 'rc.uda.githubnumber.type=numeric', 'rc.uda.githubnumber.label="Github Issue/PR #"', 'rc.uda.githubbody.type=string', 'rc.uda.githubbody.label="Github Body"', 'rc.uda.tracurl.type=string', 'rc.uda.tracurl.label="Trac URL"', 'rc.uda.githubrepo.type=string', 'rc.uda.githubrepo.label="Github Repo Slug"', 'rc.uda.githubtitle.type=string', 'rc.uda.githubtitle.label="Github Title"', 'rc.uda.tracnumber.type=numeric', 'rc.uda.tracnumber.label="Trac Number"', 'rc.uda.bugzillaurl.type=string', 'rc.uda.bugzillaurl.label="Bugzilla URL"', 'rc.uda.githuburl.type=string', 'rc.uda.githuburl.label="Github URL"', 'rc.uda.bugzillabugid.type=numeric', 'rc.uda.bugzillabugid.label="Bugzilla B
 ug ID"', 'rc.uda.githubtype.type=string', 'rc.uda.githubtype.label="Github Type"', 'rc.uda.githubmilestone.type=numeric', 'rc.uda.githubmilestone.label="Github Milestone"', 'rc.uda.tracsummary.type=string', 'rc.uda.tracsummary.label="Trac Summary"', 'rc.dependency.confirmation=no', 'rc.json.array=TRUE', 'rc.confirmation=no', 'rc.verbose=new-uuid', 'export', 'description.startswith:\\(bw\\)Is#1208031 - Android tc\\[Tier-2\\] Build problem ', '( status:pending or status:waiting )'] #2; stderr:"Invalid range end"; stdout:""
```

I admit that I'm guessing on the cause here, but this is probably the first time I've had a bug title with [..] in it.  Is that being over- or under-escaped??

**Comment by ralphbean** [comment]
Almost surely.

As an attempt at a workaround, can you try setting ``legacy_matching = False`` in the ``[general]`` section of your bugwarriorrc file?

**Comment by djmitche** [comment]
Indeed, that works

**Comment by ralphbean** [comment]
Cool.  We set that setting to False by default in the newest releases of bugwarrior.  See ralphbean/bugwarrior#241.
